
### Recuperar todos los productos
GET http://localhost:1234/products/CP0002

###Para filtrar los productos por familia y subfamilia:
GET http://localhost:1234/products?CodFamil=F123&CodSubFamil=SF123

### Recuperar un producto por ID

GET http://localhost:1234/products?CodFamil=F123&CodSubFamil=SF123

### Crear un producto con POST
POST http://localhost:1234/products
Content-Type: application/json

{
  "input":{
  "CodProdu": "CP0002",
  "DesProdu": "Electric Drill",
  "CodFamil": "Tools",
  "CodSubFamil": "Power Tools",
  "CodMarca": "DrillMaster",
  "CodTipo": "Drill",
  "Comentario": "Powerful and reliable drill, perfect for home and professional use.",
  "FecAlta": 1672020300,
  "StockSN": "Y",
  "PreCosto": 89.99
  }
}

###  Borrar un producto

DELETE http://localhost:1234/products/CP0002

###  Actualizar un producto
PATCH http://localhost:1234/products/CP0002
Content-Type: application/json

{
  "precosto": 79.99,
  "comentario": "Discounted price for clearance."
}